### ISSUE TITLE
Options are not working

### ISSUE THREAD

**Issue by boppy** [miguelmota/streamhut#5]
I can only get the binary to react to `--help`, but no of the other options work.

As stated in the docs, there should be a `streamhut server --help` option. But it only starts the server process on my Arch and an alpine-docker container I tried. Also the information I obtained from source code are not interpreted:
https://github.com/streamhut/streamhut/blob/78b537f31834b234deca19434a2f74ad73741346/cmd/streamhut/main.go#L132-L140

Since I barely know anything about Go, I cannot provide any more hints... If I can help out with testing, just drop a note.

---

*Additional Infomation*

Locally I tried the following commands (which result in a `events.js:282: throw er; // Unhandled 'error' event` because `:9000` is in use on my host):

```bash
streamhut server --port 9247
streamhut server --port=9247
streamhut server -p 9247

streamhut -p 9247 server
streamhut --port 9247 server
streamhut --port=9247 server
```

If you'd like to try it your own, here is my minimized docker example:

```Dockerfile
FROM alpine:latest

RUN apk --no-cache add npm ruby python \
    && npm config set user 0 \
    && npm config set unsafe-perm true \
    && npm install -g streamhut

EXPOSE 1337 9000

CMD ["/usr/bin/streamhut","server","--share-base-url=https://foo.example.com/"]
```

Result: Server starts but provides wrong share base url.

**Comment by miguelmota** [comment]
Hey @boppy, the node.js NPM module is deprecated in favor of the Go implementation. Check out this [Dockerfile](https://github.com/streamhut/streamhut/blob/master/Dockerfile) and then you should be able to pass environment variables like this:

```bash
$ docker build -t streamhut .
$ docker run -e PORT=8080 -e NET_PORT=1337 -p 8080:8080 -p 1337:1337 streamhut
```

**Comment by boppy** [comment]
Oops, sorry for taking outdated approaches ;) You might want to consider changing the info on https://streamhut.io/ about npm install...

I cannot get it working with env vars. I tried (from my `docker-compose.yaml`):

````
    environment:
      SHARE-BASE-URL: https://shell.example.com/
      ShareBaseUrl: https://shell.example.com/
      shareBaseUrl: https://shell.example.com/
````

In your example you mention `PORT` and `NET_PORT` while `streamhut help` names them `PORT` and `TCP_PORT`. Do the env vars differ in name from the options to the binary? Could you provide a "matching" for those?

**Comment by miguelmota** [comment]
Sorry for the confusion. The environment variables and cli options have been updated to match, so this docker-compose config should work:

```yaml
    ports:
      - "8080:8080"
      - "1337:1337"
    environment:
      - PORT=8080
      - TCP_PORT=1337
      - SHARE_BASE_URL= https://shell.example.com
```
